class Languages:
    frases = {
        "ru": {
            "ProcessedSuccess": "Обработка: успешно",
            "FindPorts": "Поиск портов",
            "PortsFound": "Найдено только %d портов",
            "ServerStarted": "Сервер запущен на %s:%d",
            "Connected": "Подключено: %s:%d",
            "SendInfo": "Передача информации",
            "TransferSpeed": "Скорость передачи файла: %s",
            "RemoveSuccess": "Удаление УСПЕШНО",
            "Removing": "Удаление ...",
            "ServerLoading": "Загрузка сервера...",
            "EnterSendFilePath": "Введите путь к файлу для отправки: ",
            "EnterServerIP": "Введите IP-адрес сервера: ",
            "EnterMainPort": "Введите основной порт: ",
            "EnterMaxPorts": "Введите максимальное количество портов:",
            "EnterMaxPacketSize": "Введите максимальный размер пакета:",
            "FilePath": "Указанный файл %s готовится к отправке",
            "PacketSize": "Размер пакета: %d",
            "HostIP": "IP-адрес хоста: %s",
            "HostPort": "Порт хоста: %d",
            "MaxPorts": "Максимальное количество портов: %d",
            "GetMode": "Выберите режим: \n1. Получение файла\n2. Отправка файла",
            "GetOptions": "Введите опции: ",
            "ClientLoading": "Загрузка клиента...",
            "EnterSavePath": "Введите путь для сохранения:",
            "DataTransferComplete": "Файл полностью получен",
            "ReceivingFile": "Получение файла",
            "HashCheck": "Проверка целостности:",
            "SendFile": "Передача файла",
            "MergeFile": "Создание файла",
            "ReceivingInfo": "Получение информации",
            "CalcHash": "Подсчёт хэша файла",
            "IPNotAvailable": "IP адрес %s:%s не доступен",
            "downFileDel": "Ошибка. Имя у файла, который будет загружен, уже существует. Заменить на новый файл [y/n]? ",
            "downFileDelAnswerNotAllowed": "Данный ответ '%s' невозможен на поставленный вопрос",
            "downProcess": "Подготовка файла",
            "FileNotFound": "Указанный файл %s не найден",
        },
        "en": {
            "ProcessedSuccess": "Processing: successful",
            "FindPorts": "Finding ports",
            "PortsFound": "Only %d ports found",
            "ServerStarted": "Server started at %s:%d",
            "Connected": "Connected: %s:%d",
            "SendInfo": "Sending information",
            "TransferSpeed": "File transfer speed: %s",
            "RemoveSuccess": "Removal SUCCESSFUL",
            "Removing": "Removing ...",
            "ServerLoading": "Loading server...",
            "EnterSendFilePath": "Enter the path to the file to send: ",
            "EnterServerIP": "Enter the server IP address: ",
            "EnterMainPort": "Enter the main port: ",
            "EnterMaxPorts": "Enter the maximum number of ports:",
            "EnterMaxPacketSize": "Enter the maximum packet size:",
            "FilePath": "The specified file %s is being prepared for sending",
            "PacketSize": "Packet size: %d",
            "HostIP": "Host IP address: %s",
            "HostPort": "Host port: %d",
            "MaxPorts": "Maximum number of ports: %d",
            "GetMode": "Select mode: \n1. Receive file\n2. Send file",
            "GetOptions": "Enter options: ",
            "ClientLoading": "Loading client...",
            "EnterSavePath": "Enter the path for saving:",
            "DataTransferComplete": "File completely received",
            "ReceivingFile": "Receiving file",
            "HashCheck": "Integrity check:",
            "SendFile": "Sending file",
            "MergeFile": "Creating file",
            "ReceivingInfo": "Receiving information",
            "CalcHash": "Calculating file hash",
            "IPNotAvailable": "IP address %s:%d is not available",
            "downFileDel": "Error. The name of the file to be downloaded already exists. Replace with a new file [y/n]? ",
            "downFileDelAnswerNotAllowed": "This answer '%s' is not allowed for the given question",
            "downProcess": "Preparing file",
            "FileNotFound": "The specified file %s was not found",
        },
        "zh": {
            "ProcessedSuccess": "处理：成功",
            "FindPorts": "查找端口",
            "PortsFound": "仅找到 %d 个端口",
            "ServerStarted": "服务器已在 %s:%d 启动",
            "Connected": "已连接：%s:%d",
            "SendInfo": "发送信息",
            "TransferSpeed": "文件传输速度：%s",
            "RemoveSuccess": "删除成功",
            "Removing": "正在删除 ...",
            "ServerLoading": "正在加载服务器...",
            "EnterSendFilePath": "请输入要发送的文件路径：",
            "EnterServerIP": "请输入服务器的 IP 地址：",
            "EnterMainPort": "请输入主端口：",
            "EnterMaxPorts": "请输入最大端口数量：",
            "EnterMaxPacketSize": "请输入最大数据包大小：",
            "FilePath": "指定的文件 %s 正在准备发送",
            "PacketSize": "数据包大小：%d",
            "HostIP": "主机 IP 地址：%s",
            "HostPort": "主机端口：%d",
            "MaxPorts": "最大端口数量：%d",
            "GetMode": "选择模式：\n1. 接收文件\n2. 发送文件",
            "GetOptions": "请输入选项：",
            "ClientLoading": "正在加载客户端...",
            "EnterSavePath": "请输入保存路径：",
            "DataTransferComplete": "文件完全接收",
            "ReceivingFile": "接收文件",
            "HashCheck": "完整性检查：",
            "SendFile": "发送文件",
            "MergeFile": "创建文件",
            "ReceivingInfo": "接收信息",
            "CalcHash": "计算文件哈希",
            "IPNotAvailable": "IP 地址 %s:%d 不可用",
            "downFileDel": "错误。要下载的文件名已存在。是否替换为新文件 [y/n]? ",
            "downFileDelAnswerNotAllowed": "该回答 '%s' 在此问题上不可用",
            "downProcess": "准备文件",
            "FileNotFound": "指定的文件 %s 未找到",
        },
        "es": {
            "ProcessedSuccess": "Procesamiento: exitoso",
            "FindPorts": "Buscando puertos",
            "PortsFound": "Solo se encontraron %d puertos",
            "ServerStarted": "Servidor iniciado en %s:%d",
            "Connected": "Conectado: %s:%d",
            "SendInfo": "Enviando información",
            "TransferSpeed": "Velocidad de transferencia de archivo: %s",
            "RemoveSuccess": "Eliminación EXITOSA",
            "Removing": "Eliminando ...",
            "ServerLoading": "Cargando servidor...",
            "EnterSendFilePath": "Ingrese la ruta del archivo a enviar: ",
            "EnterServerIP": "Ingrese la dirección IP del servidor: ",
            "EnterMainPort": "Ingrese el puerto principal: ",
            "EnterMaxPorts": "Ingrese la cantidad máxima de puertos:",
            "EnterMaxPacketSize": "Ingrese el tamaño máximo del paquete:",
            "FilePath": "El archivo especificado %s se está preparando para enviar",
            "PacketSize": "Tamaño del paquete: %d",
            "HostIP": "Dirección IP del host: %s",
            "HostPort": "Puerto del host: %d",
            "MaxPorts": "Cantidad máxima de puertos: %d",
            "GetMode": "Seleccione modo: \n1. Recibir archivo\n2. Enviar archivo",
            "GetOptions": "Ingrese opciones: ",
            "ClientLoading": "Cargando cliente...",
            "EnterSavePath": "Ingrese la ruta para guardar:",
            "DataTransferComplete": "Archivo completamente recibido",
            "ReceivingFile": "Recibiendo archivo",
            "HashCheck": "Verificación de integridad:",
            "SendFile": "Enviando archivo",
            "MergeFile": "Creando archivo",
            "ReceivingInfo": "Recibiendo información",
            "CalcHash": "Calculando hash del archivo",
            "IPNotAvailable": "La dirección IP %s:%d no está disponible",
            "downFileDel": "Error. El nombre del archivo a descargar ya existe. ¿Reemplazar por un nuevo archivo [y/n]? ",
            "downFileDelAnswerNotAllowed": "Esta respuesta '%s' no es válida para la pregunta planteada",
            "downProcess": "Preparando archivo",
            "FileNotFound": "El archivo especificado %s no fue encontrado",
        },
        "it": {
            "ProcessedSuccess": "Elaborazione: riuscita",
            "FindPorts": "Ricerca porte",
            "PortsFound": "Trovate solo %d porte",
            "ServerStarted": "Server avviato su %s:%d",
            "Connected": "Connesso: %s:%d",
            "SendInfo": "Invio informazioni",
            "TransferSpeed": "Velocità di trasferimento file: %s",
            "RemoveSuccess": "Rimozione RIUSCITA",
            "Removing": "Rimozione ...",
            "ServerLoading": "Caricamento server...",
            "EnterSendFilePath": "Inserisci il percorso del file da inviare: ",
            "EnterServerIP": "Inserisci l'indirizzo IP del server: ",
            "EnterMainPort": "Inserisci la porta principale: ",
            "EnterMaxPorts": "Inserisci il numero massimo di porte:",
            "EnterMaxPacketSize": "Inserisci la dimensione massima del pacchetto:",
            "FilePath": "Il file specificato %s è in preparazione per l'invio",
            "PacketSize": "Dimensione del pacchetto: %d",
            "HostIP": "Indirizzo IP dell'host: %s",
            "HostPort": "Porta dell'host: %d",
            "MaxPorts": "Numero massimo di porte: %d",
            "GetMode": "Seleziona modalità: \n1. Ricevi file\n2. Invia file",
            "GetOptions": "Inserisci opzioni: ",
            "ClientLoading": "Caricamento client...",
            "EnterSavePath": "Inserisci il percorso per il salvataggio:",
            "DataTransferComplete": "File completamente ricevuto",
            "ReceivingFile": "Ricezione file",
            "HashCheck": "Controllo integrità:",
            "SendFile": "Invio file",
            "MergeFile": "Creazione file",
            "ReceivingInfo": "Ricezione informazioni",
            "CalcHash": "Calcolo hash del file",
            "IPNotAvailable": "L'indirizzo IP %s:%d non è disponibile",
            "downFileDel": "Errore. Il nome del file da scaricare esiste già. Sostituire con un nuovo file [y/n]? ",
            "downFileDelAnswerNotAllowed": "Questa risposta '%s' non è consentita per la domanda posta",
            "downProcess": "Preparazione file",
            "FileNotFound": "Il file specificato %s non è stato trovato",
        },
        "pl": {
            "ProcessedSuccess": "Przetwarzanie: zakończone sukcesem",
            "FindPorts": "Wyszukiwanie portów",
            "PortsFound": "Znaleziono tylko %d portów",
            "ServerStarted": "Serwer uruchomiony na %s:%d",
            "Connected": "Połączono: %s:%d",
            "SendInfo": "Wysyłanie informacji",
            "TransferSpeed": "Prędkość transferu pliku: %s",
            "RemoveSuccess": "Usunięcie UDANE",
            "Removing": "Usuwanie ...",
            "ServerLoading": "Ładowanie serwera...",
            "EnterSendFilePath": "Wprowadź ścieżkę do pliku do wysłania: ",
            "EnterServerIP": "Wprowadź adres IP serwera: ",
            "EnterMainPort": "Wprowadź główny port: ",
            "EnterMaxPorts": "Wprowadź maksymalną liczbę portów:",
            "EnterMaxPacketSize": "Wprowadź maksymalny rozmiar pakietu:",
            "FilePath": "Określony plik %s jest przygotowywany do wysłania",
            "PacketSize": "Rozmiar pakietu: %d",
            "HostIP": "Adres IP hosta: %s",
            "HostPort": "Port hosta: %d",
            "MaxPorts": "Maksymalna liczba portów: %d",
            "GetMode": "Wybierz tryb: \n1. Odbierz plik\n2. Wyślij plik",
            "GetOptions": "Wprowadź opcje: ",
            "ClientLoading": "Ładowanie klienta...",
            "EnterSavePath": "Wprowadź ścieżkę do zapisu:",
            "DataTransferComplete": "Plik całkowicie odebrany",
            "ReceivingFile": "Odbieranie pliku",
            "HashCheck": "Sprawdzanie integralności:",
            "SendFile": "Wysyłanie pliku",
            "MergeFile": "Tworzenie pliku",
            "ReceivingInfo": "Odbieranie informacji",
            "CalcHash": "Obliczanie hasha pliku",
            "IPNotAvailable": "Adres IP %s:%d jest niedostępny",
            "downFileDel": "Błąd. Nazwa pliku, który ma być pobrany, już istnieje. Zastąpić nowym plikiem [y/n]? ",
            "downFileDelAnswerNotAllowed": "Ta odpowiedź '%s' nie jest dozwolona na zadane pytanie",
            "downProcess": "Przygotowanie pliku",
            "FileNotFound": "Określony plik %s nie został znaleziony",
        }
    }

    def __init__(self, language="en"):
        if language not in self.frases.keys():
            print(f"Language '{language}' not supported. Defaulting to 'en'.")
            self.language = "en"
        else:
            self.language = language

    def get_language(self):
        return self.language

    def get_text(self, text_name):
        lang_dict = self.frases.get(self.language, self.frases["en"])  # По умолчанию используем английский

        # Возвращаем текст по заданному идентификатору
        return lang_dict.get(text_name, text_name)  # Возвращаем сообщение, если текст не найден